### ISSUE TITLE
Rework "required" guns

### ISSUE THREAD

**Issue by florensie** [carlssonemil/coldwar#1]
In Cold War you no longer have to unlock gold for all launch weapons to earn the next camo tier. Instead, you now have to unlock gold for the same number of weapons that were available at launch in that weapon class. So to earn diamond SMGs, I would need to get five of them gold, but I could wait until a new SMG is released so I don't have to deal with the atrocity that is the KSP.

**Comment by carlssonemil** [comment]
I haven't had the time to play the game myself so I actually didn't know this. I'll look into a solution that fits the new requirements 😄

**Comment by florensie** [comment]
Here's how I found out if you're interested.
![image](https://user-images.githubusercontent.com/13403842/100543462-ab70c900-3250-11eb-86cb-dee4ea1051c2.png)

**Comment by carlssonemil** [comment]
Finally got the motivation to work on a solution for this 😄
