### ISSUE TITLE
"Suggestion" Hide Function 

### ISSUE THREAD

**Issue by JannikKru** [carlssonemil/coldwar#11]
Like in the MW Tracker, so I can hide the Weapons that are not important to get DM Ultra 

![Screenshot 2021-03-04 204757](https://user-images.githubusercontent.com/39200851/110021383-efc9a480-7d2a-11eb-828a-87e6f3052543.png)

**Comment by carlssonemil** [comment]
I'll look into it!

**Comment by carlssonemil** [comment]
Added a filter that hides the rest of the weapons in each category when that category is completed.
