### ISSUE TITLE
R1 Shadowhunter incorrent

### ISSUE THREAD

**Issue by DyonR** [carlssonemil/coldwar#15]
This are the last camo challanges for Zombies (in order or Grunge, Liquid, Brushstroke, Vintage, Fauna, Topography, Infection)

- Get 1500 Kills with the R1 Shadowhunter in Zombies.
- Get 3 or more Critical Hit Kills rapidly with the R1 Shadowhunter 50 times in Zombies.
- Kill 3 or more enemies with a single shot 50 times with the R1 Shadowhunter in Zombies.
- Get 1500 Kills with the R1 Shadowhunter when it's Pack-A-Punched in Zombies.
- Get 10 Special or Elite Eliminations with the R1 Shadowhunter in Zombies (Bosses count as 3 Eliminations).
- Get 10 kills rapidly 10 times with the R1 Shadowhunter in Zombies.
- Get 20 or more consecutive Kills with the R1 Shadowhunter without getting hit 10 times.  

This are the last camo challanges for Multiplayer (in order or Spray, Stripes, Classic, Geometric, Flora, Science, Psychedelic) (I shorted it since I didn't feel like typing it all out)
- Kill 30 enemies
- Get 50 longshot medals
- 2 kills without dying 20 times
- 50 headshots
- Kill 50 enemies that are detected, stunned, or blinded, by your Scorestreaks, Equipment, or Field Upgrades in Multiplayer.
- Get 5 One Shot Kills in a single game 10 times
- 2 rapid kills 25 times

**Comment by carlssonemil** [comment]
Fixed in #16
