### ISSUE TITLE
URL changed from coldwar.now.sh to coldwar.vercel.app and thus resets progress

### ISSUE THREAD

**Issue by CrazyIsEasy** [carlssonemil/coldwar#18]
Overnight the URL for the Cold War and Damascus tracker got changed and thus resets all progress. This is not a huge issue as I can just check all the camo boxes again but it's an inconvenience. And I wanted to make an issue post so you're aware of this.

**Comment by carlssonemil** [comment]
Well, _shit_. I did not expect that.

I'll add a popup upon visit notifying the users of this. And also look into the possibility of recovering the stored progress somehow, though very unlikely as it is tied to the URL.

**Comment by carlssonemil** [comment]
The URL change is referenced in [this changelog post](https://vercel.com/changelog/urls-are-becoming-consistent). I remember reading this and following this back in February. But I always interpreted it as currently existing **.now.sh** domains would continue to exist, but they would change all the automatic URLs to the new format, as well as blocking the creation of new **.now.sh** domains.

Also, the date on which this would be put into effect referenced in the post is **February 20th 2021**, over a month ago. Why did this get applied just now?

**Comment by carlssonemil** [comment]
I've searched for a way to access the localStorage on an inaccessible site but to no success. The browser itself stores the files locally on the computer but as far as I know that data cannot be accessed from outside the browser.

The simplest solution would be to just input all the progress from scratch, but I'd like to find a way to extract the lost data if possible 🤔

If anyone have any idea on how to go about this, it would be greatly appreciated!
