### ISSUE TITLE
"You have completed all camouflage challenges 👏" Bug

### ISSUE THREAD

**Issue by CrazyIsEasy** [carlssonemil/coldwar#4]
Since the push of Fix #1 - Rework "required" guns (#3 ) if you had the "hide non required" box checked the "You have completed all camouflage challenges 👏" string will pop up and hide the remaining camouflage challenges with no way check off camouflage challenges and no way to uncheck the "hide non required" box.

![coldwartrackerbug](https://user-images.githubusercontent.com/74504687/104464929-79f25980-5581-11eb-8404-5d7024b7cb31.PNG)

**Comment by carlssonemil** [comment]
Another user contacted me by mail earlier today with this bug, but I thought it was related to the full-screen completion. Thanks for providing accurate information and a screenshot of the issue. I pushed a fix that should solve this bug.

**Comment by CrazyIsEasy** [comment]
Wow, that was fast, thank you for the quick fix!
